export const ADD_ITEM = "ADD_ITEM";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILED = "ADD_ITEM_FAILED";

export const REMOVE_ITEM = "REMOVE_ITEM";
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS";
export const REMOVE_ITEM_FAILED = "REMOVE_ITEM_FAILED";

export const MOVE_ITEM = "MOVE_ITEM";
export const MOVE_ITEM_SUCCESS = "MOVE_ITEM_SUCCESS";
export const MOVE_ITEM_FAILED = "MOVE_ITEM_FAILED";

export const EDIT_ITEM = "EDIT_ITEM";
export const EDIT_ITEM_SUCCESS = "EDIT_ITEM_SUCCESS";
export const EDIT_ITEM_FAILED = "EDIT_ITEM_FAILED";

export const SHOW_ITEMS = "SHOW_ITEMS";
export const SHOW_ITEMS_SUCCESS = "SHOW_ITEMS_SUCCESS";
export const SHOW_ITEMS_FAILED = "SHOW_ITEMS_FAILED";
